[package]
name = "brick_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
users = "0.11"
colored = "3.0.0"
dirs = "4.0"
os_pipe = "1.2.1"
rustyline = "15.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"